### ISSUE TITLE
Can't install ROS on my Jetson Nano

### ISSUE THREAD

**Issue by jonathan84clark** [JetsonHacksNano/installROS#1]
Hello,

I have been trying to install ROS on the Jetson Nano and I am having some trouble. Can you help me with this?

Here is the what I get when I run your script:
`jonathan@jonathan-nano:~/installROS$ sudo  ./installROS.sh -p ros-melodic-desktop -p ros-melodic-rgbd-launch
Packages to install: ros-melodic-desktop ros-melodic-rgbd-launch
Adding repository and source list
'universe' distribution component is already enabled for all sources.
'multiverse' distribution component is already enabled for all sources.
'restricted' distribution component is already enabled for all sources.
Executing: /tmp/apt-key-gpghome.E60dHRCMzP/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
gpg: key F42ED6FBAB17C654: "Open Robotics <info@osrfoundation.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Updating apt-get
Get:1 file:/var/cuda-repo-10-0-local-10.0.326  InRelease
Ign:1 file:/var/cuda-repo-10-0-local-10.0.326  InRelease
Get:2 file:/var/visionworks-repo  InRelease
Ign:2 file:/var/visionworks-repo  InRelease
Get:3 file:/var/visionworks-sfm-repo  InRelease
Ign:3 file:/var/visionworks-sfm-repo  InRelease
Get:4 file:/var/visionworks-tracking-repo  InRelease
Ign:4 file:/var/visionworks-tracking-repo  InRelease
Get:5 file:/var/cuda-repo-10-0-local-10.0.326  Release [574 B]
Get:6 file:/var/visionworks-repo  Release [1,999 B]
Get:7 file:/var/visionworks-sfm-repo  Release [2,003 B]
Get:5 file:/var/cuda-repo-10-0-local-10.0.326  Release [574 B]
Get:8 file:/var/visionworks-tracking-repo  Release [2,008 B]
Get:6 file:/var/visionworks-repo  Release [1,999 B]
Get:7 file:/var/visionworks-sfm-repo  Release [2,003 B]
Get:8 file:/var/visionworks-tracking-repo  Release [2,008 B]
Hit:9 http://packages.ros.org/ros/ubuntu bionic InRelease
Hit:10 http://international.download.nvidia.com/jetson/repos/common r32 InRelease
Hit:11 http://international.download.nvidia.com/jetson/repos/t210 r32 InRelease
Hit:13 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://international.download.nvidia.com/jetson/repos/common r32 InRelease' doesn't support architecture 'armhf'
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://international.download.nvidia.com/jetson/repos/t210 r32 InRelease' doesn't support architecture 'armhf'
Installing ROS
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-melodic-desktop : Depends: ros-melodic-common-tutorials but it is not going to be installed
                       Depends: ros-melodic-geometry-tutorials but it is not going to be installed
                       Depends: ros-melodic-robot but it is not going to be installed
                       Depends: ros-melodic-ros-tutorials but it is not going to be installed
                       Depends: ros-melodic-urdf-tutorial but it is not going to be installed
                       Depends: ros-melodic-visualization-tutorials but it is not going to be installed
                       Depends: ros-melodic-viz but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-melodic-rgbd-launch : Depends: ros-melodic-depth-image-proc but it is not going to be installed
                           Depends: ros-melodic-image-proc but it is not going to be installed
                           Depends: ros-melodic-nodelet but it is not going to be installed
                           Depends: ros-melodic-tf2-ros but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

I also tried using aptitude from this forum:
https://forums.developer.nvidia.com/t/solved-ros-installation-on-jetson-nano-jetpack-4-2-ubuntu-18-04-3-lts/111615

It did not install ROS either. 

Have you ever seen anything like this? Do you have any suggestions? Do I need to re-flash my Jetson?

Thanks for the help!

Jonathan L Clark

**Comment by jonathan84clark** [comment]
Found the solution. I had to re-flash my Nano. Something I did must have messed up my system. The last big install I did was Tensor flow. I am going to try to install it again. If it messes up ROS then we may have found a root cause.

**Comment by jetsonhacks** [comment]
Closing this for now. If you encounter something, please open another issue.
